# Generated by Django 5.0.1 on 2024-01-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarian_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='library',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.librarian'),
        ),
    ]
